version: "2.1"

services:
  base:
    image: super-draft
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ./data:/app/data

  worker:
    extends:
      service: base
    command: python worker.py

  start-tournament:
    extends:
      service: base
    command: python start-tournament.py

  generate-token-pickle:
    extends:
      service: base
    command: python generate-token-pickle.py
    volumes:
      - ./credentials.json:/app/credentials.json